### GET ALL MOVIES
GET http://localhost:4545/movies
### GET A SPECIFIC MOVIE
GET http://localhost:4545/movies/id/5ad1a235-0d9c-410a-b32b-220d91689a08
### FILTER BY GENRE
GET http://localhost:4545/movies?genre=action
### GET A MOVIE BY TITLE
GET http://localhost:4545/movies/title/King
### POST A NEW MOVIE
POST http://localhost:4545/movies
Content-Type: application/json

{
    "title": "the Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ],
    "rate": 4.5
}
### PATCH A MOVIE
PATCH http://localhost:4545/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
    "title": "new title"
}
### DELETE A MOVIE
DELETE http://localhost:4545/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3